config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to, 'lists#index'
  resources :lists, only: [:index, :show, :new, :create]
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end
# get 'lists', to: 'lists#index'
# get 'lists/:id, to: 'lists#show'
# get 'lists/new', to: 'lists#new'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    # raise
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>create a new bookmark</h1>
<%= simple_form_for([@list, @bookmark]) do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.submit%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My lists</h1>
<ul>
  <% @lists.each do |list| %>
  <li><%= link_to "#{list.name}", list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>add a list please</h1>
<%= simple_form_for (@list) do |f| %>
<%= f.input :name, placeholder: "enter a list name you like" %>
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1>One of my list</h1>
<strong><%= @list.name %></strong>
<br>
<br>
<h2>add a new bookmark</h2>
<%= link_to "add a new bookmark", new_list_bookmark_path(@list) %>
<% @list.movies.each do |movie|%>
<div><%= movie.title %></div>
<% bookmark = Bookmark.find_by(list: @list) %>
<div><%= bookmark.comment %></div>
<div><%= link_to "delete the bookmark", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "are you sure?"} %></div>
<% end %>
<br>
<div>
  <%= link_to "back to my list", lists_path %>
</div>